// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "brpc/proto_base.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace brpc {

namespace {

const ::google::protobuf::Descriptor* SerializedRequestBase_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SerializedRequestBase_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_brpc_2fproto_5fbase_2eproto() {
  protobuf_AddDesc_brpc_2fproto_5fbase_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "brpc/proto_base.proto");
  GOOGLE_CHECK(file != NULL);
  SerializedRequestBase_descriptor_ = file->message_type(0);
  static const int SerializedRequestBase_offsets_[1] = {
  };
  SerializedRequestBase_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SerializedRequestBase_descriptor_,
      SerializedRequestBase::default_instance_,
      SerializedRequestBase_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SerializedRequestBase, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SerializedRequestBase, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SerializedRequestBase));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_brpc_2fproto_5fbase_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SerializedRequestBase_descriptor_, &SerializedRequestBase::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_brpc_2fproto_5fbase_2eproto() {
  delete SerializedRequestBase::default_instance_;
  delete SerializedRequestBase_reflection_;
}

void protobuf_AddDesc_brpc_2fproto_5fbase_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025brpc/proto_base.proto\022\004brpc\"\027\n\025Seriali"
    "zedRequestBase", 54);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "brpc/proto_base.proto", &protobuf_RegisterTypes);
  SerializedRequestBase::default_instance_ = new SerializedRequestBase();
  SerializedRequestBase::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_brpc_2fproto_5fbase_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_brpc_2fproto_5fbase_2eproto {
  StaticDescriptorInitializer_brpc_2fproto_5fbase_2eproto() {
    protobuf_AddDesc_brpc_2fproto_5fbase_2eproto();
  }
} static_descriptor_initializer_brpc_2fproto_5fbase_2eproto_;


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

SerializedRequestBase::SerializedRequestBase()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SerializedRequestBase::InitAsDefaultInstance() {
}

SerializedRequestBase::SerializedRequestBase(const SerializedRequestBase& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SerializedRequestBase::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SerializedRequestBase::~SerializedRequestBase() {
  SharedDtor();
}

void SerializedRequestBase::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SerializedRequestBase::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SerializedRequestBase::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SerializedRequestBase_descriptor_;
}

const SerializedRequestBase& SerializedRequestBase::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_brpc_2fproto_5fbase_2eproto();  return *default_instance_;
}

SerializedRequestBase* SerializedRequestBase::default_instance_ = NULL;

SerializedRequestBase* SerializedRequestBase::New() const {
  return new SerializedRequestBase;
}

void SerializedRequestBase::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SerializedRequestBase::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void SerializedRequestBase::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SerializedRequestBase::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SerializedRequestBase::ByteSize() const {
  int total_size = 0;
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SerializedRequestBase::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SerializedRequestBase* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SerializedRequestBase*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SerializedRequestBase::MergeFrom(const SerializedRequestBase& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SerializedRequestBase::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SerializedRequestBase::CopyFrom(const SerializedRequestBase& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SerializedRequestBase::IsInitialized() const {
  
  return true;
}

void SerializedRequestBase::Swap(SerializedRequestBase* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SerializedRequestBase::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SerializedRequestBase_descriptor_;
  metadata.reflection = SerializedRequestBase_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace brpc

// @@protoc_insertion_point(global_scope)
